name: shenfun_doc_env

channels:
  - conda-forge
  - defaults

dependencies:
  - cython
  - fftw
  - numpy
  - sympy
  - scipy
  - mpi4py
  - mpi4py-fft
  - Sphinx==2.2.*
  - pip:
    - sphinxcontrib-bibtex
